03-01-many-to-many-relationships/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
	path('profile/<username>/', views.profile, name='profile'),
	path('<int:user_pk>/follow/', views.follow, name="follow"),
]

03-01-many-to-many-relationships/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    followings = models.ManyToManyField('self', symmetrical=False, related_name='followers')

03-01-many-to-many-relationships/accounts/views.py
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import update_session_auth_hash, get_user_model
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.shortcuts import redirect, render

from .forms import CustomUserChangeForm, CustomUserCreationForm


# Create your views here.
def login(request):
    if request.user.is_authenticated:
        return redirect('articles:index')

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('articles:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


def logout(request):
    auth_logout(request)
    return redirect('articles:index')


def signup(request):
    if request.user.is_authenticated:
        return redirect('articles:index')

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('articles:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


def delete(request):
    request.user.delete()
    return redirect('articles:index')


def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('articles:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/update.html', context)


def change_password(request, user_pk):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('articles:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/change_password.html', context)

def profile(request, username):
    User = get_user_model()
    person = User.objects.get(username=username)
    context = {
        'person':person,
    }
    return render(request, 'accounts/profile.html', context)

def follow(request, user_pk):
    User = get_user_model()
    person = User.objects.get(pk=user_pk)
    # 스스로는 팔로우 불가
    if person != request.user:  # 로그인한 사용자와 다른 pk라면
        # 팔로우 안된 경우
        if person.followers.filter(pk=request.user.pk).exists():
            person.followers.remove(request.user)
        else:
            person.followers.add(request.user)
    return redirect('accounts:profile', person.username)

03-01-many-to-many-relationships/accounts/templates/accounts/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
</head>
<body>
	{% if request.user.is_authenticated %}
	<a href="{% url "articles:index" %}">HOME</a>
    <a href="{% url "articles:create" %}">CREATE</a>
    <form action="{% url "accounts:logout" %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="로그아웃">
    </form>
    <form action="{% url "accounts:delete" %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="회원탈퇴">
    </form>
    <a href="{% url "accounts:update" %}">회원정보 수정</a>
	{% else %}
    <a href="{% url "accounts:login" %}">로그인</a>
    <a href="{% url "accounts:signup" %}">회원가입</a>
{% endif %}

	<h1>{{ person.username }}의 프로필 페이지</h1>
	<form action="{% url "accounts:follow" person.pk %}" method="POST">
		{% csrf_token %}
		{% if request.user in person.followers.all %}
		<input type="submit" value="🤝">
		{% else %}
		<input type="submit" value="🙅‍♀️">
		{% endif %}
	</form>
	<p>팔로워 수 | {{ person.followers.count }} / 팔로잉 수 | {{ person.followings.count }}</p>
	<hr>
	
	<h2>{{ person.username }}이 작성한 게시물</h2>
	{% for article in person.article_set.all %}
	<div>• {{ article.title }}</div>
	{% endfor %}

	<h2>{{ person.username }}이 좋아요 한 게시글</h2>
	{% for article in person.like_articles.all %}
	<div>• {{ article.title }}</div>
	{% endfor %}
</body>
</html>